pipeline {
    agent {
        label 'agent'
    }

    environment {
        GIT_URL = "https://github.com/SonarSource/sonar-scanning-examples.git"
        BUILD_PATH = 'sonarqube-scanner-gradle/gradle-basic'
    }

    parameters {
        // string(name: 'buildEnv', defaultValue: 'gradle', description: 'Build environment')
        // string(name: 'language', defaultValue: 'java', description: 'Programming language')
        string(name: 'GIT_BRANCH', defaultValue: 'master', description: 'Git branch')
        string(name: 'commitHash', defaultValue: 'hash1231241421', description: 'Input commit hash to build')
    }

    // parameters {
    //     number(name: 'PRIORITY', defaultValue: 5, description: 'Set the build priority. This can be from 1 to 10, with higher numbers indicating higher priority.')
    // }

    // options {
    //     priority(params.PRIORITY)
    // }

    stages {

        stage('Check Commit Hash') {
            steps {
                script {
                    targetCommit = params.commitHash.trim()
                    if(targetCommit == '') { // commit hash 값이 입력되지 않았을 경우.
                        // 사용자 지정 브랜치에서 가장 최근 commit hash 값을 얻어옴.
                        targetCommit = sh(script: "git ls-remote ${GIT_URL} ${params.GIT_BRANCH} | awk '{print \$1}'", returnStdout: true).trim()
                        if(targetCommit == '') {    // 브랜치 이름이 존재하지 않을 경우 빌드 중지
                            echo "Can't find target branch's commit hash"
                            currentBuild.result = 'ABORTED'
                            error("Build was aborted because the ${params.GIT_BRANCH} branch doesn't exist.")
                        }
                        echo "targetCommit: ${targetCommit}"
                        echo "Latest commit hash for branch ${params.GIT_BRANCH}: ${targetCommit}"
                    } else {
                        echo "User provided commit hash: ${targetCommit}"
                    }

                    def buildStatusUrl = "${env.JENKINS_URL}/job/${env.JOB_NAME}/api/json?tree=allBuilds[result,actions[buildsByBranchName[*[*]]]]"
                    def buildStatusResponse = httpRequest(url: buildStatusUrl, authentication: AUTHENTICATION_ID, acceptType: 'APPLICATION_JSON')
                    def buildStatusJson = readJSON text: buildStatusResponse.content

                    def commitBuilt = false
                    for (build in buildStatusJson.allBuilds) {
                        def branchBuildInfo = build.actions.find { it.buildsByBranchName }
                        if (branchBuildInfo) {
                            def commitInfo = branchBuildInfo.buildsByBranchName.values().find { it.revision.SHA1.startsWith(targetCommit) }
                            if (commitInfo && build.result == 'SUCCESS') {
                                commitBuilt = true
                                break
                            }
                        }
                    }

                    if (commitBuilt) {
                        echo "Target commit ${targetCommit} was built successfully. Stopping the build."
                        currentBuild.result = 'ABORTED'
                        error("Build was aborted because the target commit ${targetCommit} has already been built successfully.")
                    } else {
                        echo "Target commit ${targetCommit} was not built or not built successfully. Continuing the build."
                    }
                }
            }
        }

        stage('Set Environment Variables') {
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'sonar_login', variable: 'SONAR_LOGIN'),
                        string(credentialsId: 'sonar_password', variable: 'SONAR_PASSWORD'),
                        string(credentialsId: 'sonar_port', variable: 'SONAR_PORT'),
                        string(credentialsId: 'jenkins_port', variable: 'JENKINS_PORT'),
                        string(credentialsId: 'authentication_id', variable: 'AUTHENTICATION_ID'),
                        string(credentialsId: 'host_bind_mount', variable: 'HOST_BIND_MOUNT')
                    ]) {
                        env.SONAR_LOGIN = "${SONAR_LOGIN}"
                        env.SONAR_PASSWORD = "${SONAR_PASSWORD}"
                        env.SONAR_PORT = "${SONAR_PORT}"
                        env.JENKINS_PORT = "${JENKINS_PORT}"
                        env.AUTHENTICATION_ID = "${AUTHENTICATION_ID}"
                        env.HOST_BIND_MOUNT = "${HOST_BIND_MOUNT}"
                    }
                }
            }
        }

        stage('Clone Repository') {
            steps {
                script {
                    // Replace 'BRANCH_NAME' with the desired branch name
                    def BRANCH_NAME = params.GIT_BRANCH

                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: "${BRANCH_NAME}"]],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [[$class: 'CloneOption', noTags: false, shallow: false, depth: 0, reference: '']],
                        submoduleCfg: [],
                        userRemoteConfigs: [[url: "${GIT_URL}", refspec: "+refs/heads/${BRANCH_NAME}:refs/remotes/origin/${BRANCH_NAME}"]]
                    ])

                    sh "git checkout ${targetCommit}"
                }
            }
        }


        stage('Launch Sonarqube container') {
            steps {
                echo '정적검사를 위한 소나큐브 컨테이너를 띄웁니다.'
                sh 'docker run --rm -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p ${SONAR_PORT}:9000 sonarqube:latest'
                script {
                    env.SONAR_HOST = "http://${sh(script:'docker exec sonarqube hostname -I', returnStdout: true).trim()}:${SONAR_PORT}"
                    waitForSonarQube("${SONAR_HOST}", 300)
                }
            }
        }

        stage('Get Sonarqube token') {
            steps {
                echo '소나큐브 토큰을 받아 환경변수로 저장합니다.'
                script {
                    def tokenOutput = sh(script: '''
                        USER_LOGIN=admin
                        TOKEN_NAME="My Jenkins Token"
                        MAX_RETRIES=12
                        RETRY_INTERVAL=5

                        for i in $(seq 1 $MAX_RETRIES); do
                            echo "Attempt #$i to get token..."
                            TOKEN=$(curl -s -u "${SONAR_LOGIN}:${SONAR_PASSWORD}" -X POST "${SONAR_HOST}/api/user_tokens/generate" \
                                -d "name=${TOKEN_NAME}" \
                                -d "login=${USER_LOGIN}" \
                                | sed -n 's/.*\"token\":\"\\([^\"]*\\)\".*/\\1/p')
                            if [ -n "$TOKEN" ]; then
                                echo "Token: ${TOKEN}"
                                break
                            else
                                echo "Token not received, waiting for $RETRY_INTERVAL seconds before retrying..."
                                sleep $RETRY_INTERVAL
                            fi
                        done

                        if [ -z "$TOKEN" ]; then
                            echo "Failed to get token after $MAX_RETRIES attempts."
                            exit 1
                        fi

                        echo "Token: ${TOKEN}"
                    ''', returnStdout: true).trim()

                    env.SONAR_TOKEN = tokenOutput.substring(tokenOutput.lastIndexOf("Token: ") + 7)
                    echo "Token: ${SONAR_TOKEN}"
                }
            }
        }

        stage('Sonarqube Scan') {
            steps {
                echo '소나큐브 정적검사를 실행합니다.'
                dir("${BUILD_PATH}") {
                    script {
                        // Get the project key
                        env.COMMIT_HASH = sh(script: "git ls-remote ${GIT_URL} HEAD | awk '{print \$1}'", returnStdout: true).trim()

                        // Get the repository name
                        def repositoryName = sh(script: "basename -s .git ${GIT_URL}", returnStdout: true).trim()

                        // Run the analysis
                        sh """
                            ./gradlew sonar \\
                                -Dsonar.host.url=${SONAR_HOST} \\
                                -Dsonar.login=${SONAR_LOGIN} \\
                                -Dsonar.password=${SONAR_PASSWORD} \\
                                -Dsonar.projectKey=${COMMIT_HASH} \\
                                -Dsonar.projectName=${repositoryName} \\
                                -Dsonar.projectVersion=1.0 \\
                                -Dsonar.scm.disabled=true \\
                                -Dsonar.analysis.mode=publish \\
                                -Dsonar.verbose=true
                        """
                    }
                }
            }
        }

        stage('Sonarqube Quality Gate') {
            steps {
                script {
                    // Wait for analysis report to be processed by SonarQube
                    def waitTime = 0
                    def maxWaitTime = 60
                    def analysisStatus = 'NONE'
                    while (analysisStatus == 'NONE' && waitTime < maxWaitTime) {
                        def jsonAnalysis = sh(script: "curl -s ${SONAR_HOST}/api/qualitygates/project_status?projectKey=${COMMIT_HASH} -u ${SONAR_LOGIN}:${SONAR_PASSWORD}", returnStdout: true).trim()
                        analysisStatus = new groovy.json.JsonSlurper().parseText(jsonAnalysis).projectStatus.status
                        if (analysisStatus == 'NONE') {
                            echo 'Analysis report is still being processed by SonarQube, waiting for 10 seconds...'
                            sleep(10)
                            waitTime += 10
                        }
                    }

                    if (waitTime >= maxWaitTime) {
                        error('Timeout waiting for analysis report to be processed by SonarQube')
                    }

                    // Check quality gate status
                    if (analysisStatus == 'WARN') {
                        echo "Quality gate status: WARN. Aborting..."
                        exit pipeline
                    } else if (analysisStatus == 'ERROR') {
                        echo "Quality gate status: ERROR. Aborting..."
                        exit pipeline
                    }
                    echo "********** Quality gate status: ${analysisStatus} **********"
                    echo '정적검사를 통과하였습니다.'
                }
            }
        }

        stage('Save Sonarqube Report') {
            steps {
                echo '소나큐브 결과를 파일로 저장합니다.'
                script {
                    def metrics = 'ncloc,coverage,violations,complexity,bugs,vulnerabilities,code_smells,sqale_index,alert_status,reliability_rating,security_rating'
                    def apiUrl = "${SONAR_HOST}/api/measures/component?component=${COMMIT_HASH}&metricKeys=${metrics}"
                    def jsonData = sh(script: "curl -s -u ${SONAR_LOGIN}:${SONAR_PASSWORD} '${apiUrl}'", returnStdout: true).trim()

                    def qualityGateApiUrl = "${SONAR_HOST}/api/qualitygates/project_status?projectKey=${COMMIT_HASH}"
                    def qualityGateJsonData = sh(script: "curl -s -u ${SONAR_LOGIN}:${SONAR_PASSWORD} '${qualityGateApiUrl}'", returnStdout: true).trim()

                    def reportData = readJSON text: jsonData
                    def qualityGateData = readJSON text: qualityGateJsonData
                    def qualityGateStatus = qualityGateData['projectStatus']['status']

                    def tableRows = reportData['component']['measures'].collect { measure ->
                        """
                            <tr>
                                <td>${measure['metric']}</td>
                                <td>${measure['value']}</td>
                            </tr>
                        """
                    }.join("")

                    def html = """
                        <html>
                            <head>
                                <title>SonarQube Report</title>
                                <style>
                                    body {
                                        font-family: Arial, sans-serif;
                                    }
                                    h1 {
                                        font-size: 24px;
                                    }
                                    h2 {
                                        font-size: 20px;
                                        margin-bottom: 10px;
                                    }
                                    table {
                                        border-collapse: collapse;
                                        width: 100%;
                                    }
                                    th, td {
                                        border: 1px solid #ddd;
                                        padding: 8px;
                                        text-align: left;
                                    }
                                    th {
                                        background-color: #f2f2f2;
                                        font-weight: bold;
                                    }
                                </style>
                            </head>
                            <body>
                                <h1>SonarQube Report</h1>
                                <h2>SonarQube Quality Gate Status: ${qualityGateStatus}</h2>
                                <h2>Report Data</h2>
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Metric</th>
                                            <th>Value</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        ${tableRows}
                                    </tbody>
                                </table>
                            </body>
                        </html>
                    """
                    writeFile file: 'sonarqube-report.html', text: html
                }
            }
        }

        stage('Save Report') {
            steps {
                echo '저장된 결과파일을 archiveArtifacts로 저장합니다.'
                archiveArtifacts artifacts: 'sonarqube-report.html', fingerprint: true
            }
        }

        stage('Build') {
            steps {
                script {
                    echo '빌드 컨테이너에서 빌드를 진행합니다.'
                    sh 'docker run --rm -v ${HOST_BIND_MOUNT}/${JOB_NAME}:/home/tmp/workspace/ openjdk:11 sh -c "cd /home/tmp/workspace/${BUILD_PATH}; sh gradlew clean build 2>&1 | tee jenkins_build_log"'
                }
            }
            post {
                failure {
                    script {
                        // 실패했는데 로그에 FAILED가 안찍히면 끝까지 못간것 -> 끝까지 가기전에 뭔가 외부요인이 개입
                        echo "BUILD FAILED!"
                        if (!readFile('jenkins_build_log').contains("FAILED")) {
                            // 최우선 순위로 재요청
                            // build job: env.JOB_NAME, parameters: [number(name: 'PRIORITY', value: 10)], wait: true
                            build job: env.JOB_NAME, wait: true
                            exit pipeline
                        }
                    }
                }
            }
        }

        stage('deploy artifacts') {
            steps {
                archiveArtifacts artifacts: "${BUILD_PATH}/build/libs/*", followSymlinks: false
            }
        }
    }

    post {
        always {
          script {
            sh 'docker stop sonarqube'
            cleanWs deleteDirs: true
            // dir("${env.WORKSPACE}/..") {
            //     sh 'find . -type d -name "pipeline-*_ws-cleanup_*" -exec rm -r {} \\;'
            // }
        //   withEnv(['USER=root']) {
        //       sh 'whoami'
        //       sh 'cd ..'
        //       sh 'pwd'
        //       sh "find . -type d -name 'pipeline-*_ws-cleanup_*' -exec rm -r {} \\;"
        //   }
          }
        }
    }
}

def waitForSonarQube(sonarQubeUrl, timeout) {
    def running = false

    for (int i = 0; i < timeout && !running; i += 10) {
        echo "Attempting to connect to SonarQube at ${sonarQubeUrl}"
        try {
            sh(script: "curl --max-time 10 --retry 0 --retry-max-time 10 --retry-connrefused --fail --silent ${sonarQubeUrl}/api/system/status", returnStdout: true)
            running = true
        } catch (Exception e) {
            sleep(10)
        }
    }

    if (!running) {
        error("SonarQube did not start within the expected time.")
    }
}