---
- name: Join node to Kubernetes cluster
  hosts: join-node
  become: true

  tasks:
  - name: Get k8s token and control plane endpoint
    shell: kubeadm token create --print-join-command
    register: k8s_join_command
    delegate_to: "{{groups['k8s-master'][0]}}"

  - name: Join node to Kubernetes cluster
    shell: "{{ k8s_join_command.stdout }}"
